package net.subsloth.database

import android.content.Context
import androidx.test.platform.app.InstrumentationRegistry
import org.junit.After
import org.junit.Assert.assertNotNull
import org.junit.Before
import org.junit.Test

/**
 * Basic Android instrumented test verifying that [createSubSlothDatabase]
 * succeeds on a real Android device/emulator after [AndroidContext] is
 * initialised.
 *
 * This guards against the `NoSuchMethodError` that occurred when the
 * Room 3 KMP inline `databaseBuilder` expansion generated bytecode
 * incompatible with `room3-runtime-android`.
 */
class AndroidDatabaseCreationTest {

    private lateinit var appContext: Context
    private lateinit var database: SubSlothDatabase

    @Before
    fun setUp() {
        appContext = InstrumentationRegistry.getInstrumentation().targetContext
        AndroidContext.init(appContext)
        database = createSubSlothDatabase("test_subsloth_db")
    }

    @After
    fun tearDown() {
        database.close()
        appContext.deleteDatabase("test_subsloth_db")
        AndroidContext.reset()
    }

    @Test
    fun database_is_created() {
        assertNotNull(database)
    }

    @Test
    fun database_has_cachedCatalogDao() {
        val dao = database.cachedCatalogDao()
        assertNotNull(dao)
    }
}
