#!/usr/bin/env bash
#
# export-readme-screenshots.sh
#
# Copies selected golden images from the Compose Preview Screenshot Testing
# framework to docs/screenshots/ for use in README.md.
#
# Run AFTER regenerating goldens:
#   ./gradlew :androidApp:connectedDebugAndroidTest \
#     -Pandroid.test.screenshot.update.golden=true
#
# Usage:
#   ./scripts/screenshots/export-readme-screenshots.sh
#
# Mapping:
#   Golden image filenames follow the convention
#     {FunctionName}_{PreviewName}.png
#   generated by compose-screenshot (com.android.compose.screenshot).
#
# Only the subset used in README.md is exported.  Update the MAPPING
# array below when adding/removing screenshots from the README.
#

set -o errexit -o nounset -o pipefail

repo_root="$(cd "$(dirname "$0")/../.." && pwd)"
goldens_dir="$repo_root/androidApp/src/screenshotTest/goldens"
docs_dir="$repo_root/docs/screenshots"

if [[ ! -d "$goldens_dir" ]]; then
  echo "[WARN] Golden images directory not found at $goldens_dir"
  echo "       Creating empty directory. Run screenshot tests with update flag to generate goldens:"
  echo "       ./gradlew :androidApp:connectedDebugAndroidTest -Pandroid.test.screenshot.update.golden=true"
  mkdir -p "$goldens_dir"
fi

mkdir -p "$docs_dir"

# ── Mapping: golden filename → docs/screenshots/ filename ──────────────
# These map the @PreviewTest function + @Preview name to the README asset.
declare -A MAPPING=(
  # Home — all three form factors, both themes
  ["HomeScreenLightScreenshot_Phone.png"]="home-light-phone.png"
  ["HomeScreenLightScreenshot_Tablet.png"]="home-light-tablet.png"
  ["HomeScreenLightScreenshot_TV.png"]="home-light-tv.png"
  ["HomeScreenDarkScreenshot_Phone.png"]="home-dark-phone.png"
  ["HomeScreenDarkScreenshot_Tablet.png"]="home-dark-tablet.png"
  ["HomeScreenDarkScreenshot_TV.png"]="home-dark-tv.png"

  # Movie detail — phone only, both themes
  ["MovieDetailLightScreenshot_Phone.png"]="movie-light-phone.png"
  ["MovieDetailDarkScreenshot_Phone.png"]="movie-dark-phone.png"

  # Series detail — tablet only, both themes
  ["SeriesDetailLightScreenshot_Tablet.png"]="series-light-tablet.png"
  ["SeriesDetailDarkScreenshot_Tablet.png"]="series-dark-tablet.png"

  # Player — phone only, both themes
  ["PlayerScreenLightScreenshot_Phone.png"]="player-light-phone.png"
  ["PlayerScreenDarkScreenshot_Phone.png"]="player-dark-phone.png"

  # Downloads — phone only, both themes
  ["DownloadsScreenLightScreenshot_Phone.png"]="downloads-light-phone.png"
  ["DownloadsScreenDarkScreenshot_Phone.png"]="downloads-dark-phone.png"
)

copied=0
missing=0

for golden_name in "${!MAPPING[@]}"; do
  docs_name="${MAPPING[$golden_name]}"

  # The golden file may be flat in goldens_dir or in a per-class subdirectory.
  # Search recursively for the filename.
  src=$(find "$goldens_dir" -name "$golden_name" -print -quit 2>/dev/null || true)

  if [[ -z "$src" ]]; then
    echo "[WARN] Golden not found: $golden_name — skipping $docs_name"
    ((missing++))
    continue
  fi

  if [[ ! -f "$src" ]]; then
    echo "[WARN] Golden path is not a file: $src — skipping $docs_name"
    ((missing++))
    continue
  fi

  cp "$src" "$docs_dir/$docs_name"
  echo "[OK]   $golden_name → $docs_name"
  ((copied++))
done

echo ""
echo "Done — $copied screenshots exported, $missing missing."

if (( missing > 0 )); then
  echo "Generate missing goldens by running screenshot tests with the update flag."
  if (( copied == 0 )); then
    echo "[WARN] No screenshots exported — this is expected on first run before goldens are generated."
  fi
fi
